# Generated by Django 4.0.2 on 2022-04-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_newpost_likes_newpost_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='newpost',
            old_name='Post',
            new_name='post',
        ),
    ]
